const COMPANY_STATUS = Object.freeze({
  PENDING: "PENDING",
  ACTIVE: "ACTIVE",
  INACTIVE: "INACTIVE",
  SUSPENDED: "SUSPENDED",
  REJECTED: "REJECTED",
});

const BARCODE_BATCH_STATUS = Object.freeze({
  DRAFT: "DRAFT",
  ACTIVE: "ACTIVE",
  EXPIRED: "EXPIRED",
  CANCELLED: "CANCELLED",
});

const BARCODE_STATUS = Object.freeze({
  ACTIVE: "ACTIVE",
  REDEEMED: "REDEEMED",
  EXPIRED: "EXPIRED",
  BLOCKED: "BLOCKED",
});

const WALLET_TRANSACTION_TYPE = Object.freeze({
  BARCODE_REWARD: "BARCODE_REWARD",
  MANUAL_REWARD: "MANUAL_REWARD",
  WITHDRAWAL_DEBIT: "WITHDRAWAL_DEBIT",
  WITHDRAWAL_REVERSAL: "WITHDRAWAL_REVERSAL",
});

const WALLET_TRANSACTION_STATUS = Object.freeze({
  SUCCESS: "SUCCESS",
  PENDING: "PENDING",
  FAILED: "FAILED",
  REVERSED: "REVERSED",
});

const WITHDRAWAL_STATUS = Object.freeze({
  PENDING: "PENDING",
  APPROVED: "APPROVED",
  REJECTED: "REJECTED",
  PAID: "PAID",
  FAILED: "FAILED",
});

module.exports = {
  BARCODE_BATCH_STATUS,
  BARCODE_STATUS,
  COMPANY_STATUS,
  WALLET_TRANSACTION_STATUS,
  WALLET_TRANSACTION_TYPE,
  WITHDRAWAL_STATUS,
};
